application: test-work-amt
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: application/static

- url: /google/admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: .*
  script: run.application.app

libraries:
- name: jinja2
  version: "2.6"
